name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  tests:
    name: PHP ${{ matrix.php }}, SF ${{ matrix.symfony }} - ${{ matrix.deps }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1]
        deps: [hightest]
        symfony: [5.4.*, 6.0.*]
        include:
          - php: 8.0
            deps: lowest
            symfony: '*'
          - php: 8.1
            deps: highest
            symfony: 6.1.*
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: flex

      - name: Restrict psr/simple-cache on Symfony 5.4
        if: ${{ matrix.symfony == '5.4.*' }}
        run: composer require --dev psr/simple-cache:"^1.0|^2.0" --no-update

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.deps }}
          composer-options: --prefer-dist
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Test
        run: vendor/bin/phpunit -v

  code-coverage:
    uses: zenstruck/.github/.github/workflows/php-coverage-codecov.yml@main
    with:
      php: 8.1

  composer-validate:
    uses: zenstruck/.github/.github/workflows/php-composer-validate.yml@main

  cs-check:
    uses: zenstruck/.github/.github/workflows/php-cs-fixer.yml@main
    with:
      php: 8.0

  sca:
    uses: zenstruck/.github/.github/workflows/php-stan.yml@main
    with:
      php: 8.1
